const CASE_DATA={
meta:{
  title:'Citibank Indonesia: 117 Transfer',
  role:'Tim review forensik independen yang melapor kepada Komite Audit',
  mission:'Menilai bagaimana transaksi yang dipersoalkan dapat melewati proses bank, bukti apa yang mendukung atau membatasi kesimpulan, dan kontrol apa yang harus diperbaiki.',
  warning:'Kasus ini menggunakan bukti publik autentik, data turunan dari sumber publik, dan rekonstruksi pembelajaran. Kegagalan proses atau kontrol tidak boleh disamakan dengan kesalahan pidana individu.',
  learning:[
    'Merekonstruksi alur transaksi dan titik pengendalian dalam sistem perbankan.',
    'Membedakan desain kontrol, pelaksanaan kontrol, override, dan keterbatasan bukti.',
    'Menilai kualitas bukti berdasarkan sumber, relevansi, keandalan, dan cakupan.',
    'Mengidentifikasi prosedur lanjutan yang diperlukan sebelum mengambil kesimpulan.',
    'Membedakan kesimpulan audit/kontrol dari kesimpulan hukum.'
  ]
},
releaseStages:[
  {stage:1,title:'Tahap 1 — Keluhan & Data Awal',desc:'Briefing dan subset transaksi terverifikasi tersedia.'},
  {stage:2,title:'Tahap 2 — Proses & Pengendalian',desc:'Terbuka setelah minimal tiga transaksi ditelaah.'},
  {stage:3,title:'Tahap 3 — Wawancara & Bukti Tambahan',desc:'Terbuka setelah minimal dua artefak kontrol ditelaah.'},
  {stage:4,title:'Tahap 4 — Disposisi Hukum & Kesimpulan',desc:'Terbuka setelah minimal tiga sumber wawancara ditelaah.'}
],
transactions:[
{id:'TX-001',date:'10 Mei 2010',form:'—',sender:'Rohli bin Pateni',senderAcc:'8000••2818',beneficiary:'Vigor Aw Yoshuara',beneficiaryAcc:'1462••0888',bank:'BCA Kuta Bali',amount:'Rp500.000.000',narrative:'—',source:'Putusan MA 1607 K/PID.SUS/2012 / catatan perkara terkait',sourceUrl:'https://putusan3.mahkamahagung.go.id/direktori/putusan/b3eadb9806be6073c8dc468767cf2da5.html',prov:'primary',confidence:'Tinggi',note:'Field yang ditampilkan dibatasi pada informasi yang telah dapat diverifikasi dari catatan publik.'},
{id:'TX-002',date:'31 Agustus 2010',form:'AM 93712',sender:'Rohli bin Pateni',senderAcc:'8000••2818',beneficiary:'Sukardi',beneficiaryAcc:'8006••1109',bank:'Citibank N.A.',amount:'USD 150.000',narrative:'—',source:'Putusan MA 1607 K/PID.SUS/2012',sourceUrl:'https://putusan3.mahkamahagung.go.id/direktori/putusan/b3eadb9806be6073c8dc468767cf2da5.html',prov:'primary',confidence:'Tinggi',note:'Nomor rekening dimasking pada tampilan mahasiswa.'},
{id:'TX-003',date:'29 September 2010',form:'AM 124134',sender:'Rohli bin Pateni',senderAcc:'8000••2818',beneficiary:'PT Graha Putranusa',beneficiaryAcc:'1040••2798',bank:'Bank Mandiri',amount:'USD 6.200',narrative:'pembayaran tower 3 lantai 22A',source:'Putusan MA 1607 K/PID.SUS/2012',sourceUrl:'https://putusan3.mahkamahagung.go.id/direktori/putusan/b3eadb9806be6073c8dc468767cf2da5.html',prov:'primary',confidence:'Tinggi',note:'Narasi transaksi dapat digunakan untuk menguji konsistensi tujuan transfer dengan profil nasabah.'},
{id:'TX-004',date:'1 Oktober 2010',form:'124135',sender:'Rohli bin Pateni',senderAcc:'8000••2818',beneficiary:'PT Exclusive Jaya Perkasa',beneficiaryAcc:'4363••8782',bank:'Belum terverifikasi',amount:'Belum terverifikasi',narrative:'—',source:'Putusan MA 1607 K/PID.SUS/2012',sourceUrl:'https://putusan3.mahkamahagung.go.id/direktori/putusan/b3eadb9806be6073c8dc468767cf2da5.html',prov:'primary',confidence:'Sedang',note:'Baris ini sengaja mempertahankan field yang belum terverifikasi sebagai “belum terverifikasi”, bukan diisi dengan asumsi.'},
{id:'TX-005',date:'16 Desember 2010',form:'110423',sender:'Ahmad Riyad',senderAcc:'8000••7838',beneficiary:'Ismail bin Janim',beneficiaryAcc:'2761••4762',bank:'BCA',amount:'Rp61.000.000',narrative:'untuk pembelian propolis Bpk A. Riyad',source:'Putusan MA / catatan perkara terkait',sourceUrl:'https://putusan3.mahkamahagung.go.id/direktori/putusan/b3eadb9806be6073c8dc468767cf2da5.html',prov:'primary',confidence:'Tinggi',note:'Salah satu contoh transaksi yang dapat dipakai untuk membandingkan narasi dengan hubungan penerima.'},
{id:'TX-006',date:'28 Desember 2010',form:'—',sender:'Gaby M',senderAcc:'2150••4146',beneficiary:'Ismail bin Janim',beneficiaryAcc:'2761••4762',bank:'BCA',amount:'Rp300.000.000',narrative:'DP untuk apartemen Regata',source:'Putusan MA / catatan perkara terkait',sourceUrl:'https://putusan3.mahkamahagung.go.id/direktori/putusan/b3eadb9806be6073c8dc468767cf2da5.html',prov:'primary',confidence:'Tinggi',note:'Penerima yang sama muncul pada lebih dari satu pengirim dalam subset.'},
{id:'TX-007',date:'Tanggal belum terverifikasi',form:'—',sender:'Collin Latung',senderAcc:'8000••1490',beneficiary:'Ismail bin Janim',beneficiaryAcc:'2761••4762',bank:'BCA',amount:'USD 10.000',narrative:'pembayaran Bpk Collin Latung untuk pembelian obat',source:'Putusan PK 99 PK/Pid.Sus/2016 / catatan terkait',sourceUrl:'https://putusan3.mahkamahagung.go.id/direktori/putusan/403cf367970d94f69c977b72679fb80e.html',prov:'primary',confidence:'Sedang',note:'Tanggal belum dipastikan dari ekstraksi publik yang tersedia saat pengembangan.'}
],
controls:[
{id:'C-01',releaseStage:2,title:'Transaction Verification SOP',fact:'Putusan terkait menyebut SOP Transaction Verification No. 30 Revision 2007.',objective:'Memastikan instruksi transfer memenuhi persyaratan verifikasi sebelum diproses.',question:'Bukti apa yang harus tersedia untuk menunjukkan bahwa verifikasi bukan hanya tercatat, tetapi benar-benar dilakukan secara memadai?',source:'Putusan 99 PK/Pid.Sus/2016',sourceUrl:'https://putusan3.mahkamahagung.go.id/direktori/putusan/403cf367970d94f69c977b72679fb80e.html',prov:'primary',reliability:'Tinggi'},
{id:'C-02',releaseStage:2,title:'Pemisahan peran',fact:'Catatan perkara mengidentifikasi peran Cash Officer dan Cash Supervisor di cabang Landmark.',objective:'Memisahkan input/pemrosesan transaksi dari fungsi supervisi atau verifikasi.',question:'Apakah keberadaan dua jabatan otomatis berarti segregation of duties efektif? Bukti operasi kontrol apa yang masih diperlukan?',source:'Putusan 99 PK/Pid.Sus/2016',sourceUrl:'https://putusan3.mahkamahagung.go.id/direktori/putusan/403cf367970d94f69c977b72679fb80e.html',prov:'primary',reliability:'Tinggi'},
{id:'C-03',releaseStage:2,title:'Verifikasi transaksi bernilai besar',fact:'Catatan perkara menyebut 18 formulir transfer melewati seorang Cash Supervisor; delapan transaksi di atas Rp300 juta diverifikasi olehnya.',objective:'Memberi lapis verifikasi tambahan atas transaksi bernilai material.',question:'Apakah konsentrasi verifikasi pada satu supervisor merupakan kelemahan, indikator beban kerja, atau hal normal? Data pembanding apa yang dibutuhkan?',source:'Putusan 99 PK/Pid.Sus/2016',sourceUrl:'https://putusan3.mahkamahagung.go.id/direktori/putusan/403cf367970d94f69c977b72679fb80e.html',prov:'primary',reliability:'Tinggi'},
{id:'C-04',releaseStage:3,title:'Uji forensik tanda tangan',fact:'Putusan PK menyebut dua formulir transaksi yang diperiksa laboratorium forensik dinilai tidak identik dengan tanda tangan asli nasabah terkait.',objective:'Menguji autentisitas otorisasi tertulis.',question:'Seberapa jauh hasil atas dua formulir dapat digeneralisasi? Bagaimana Anda akan memilih sampel atau memperluas pengujian?',source:'Putusan 99 PK/Pid.Sus/2016',sourceUrl:'https://putusan3.mahkamahagung.go.id/direktori/putusan/403cf367970d94f69c977b72679fb80e.html',prov:'primary',reliability:'Tinggi'},
{id:'C-05',releaseStage:3,title:'Inventaris bukti operasional',fact:'Catatan perkara mencantumkan account summary, banking relationship summary, guest logbook, dan dokumen kepegawaian sebagai bagian bukti.',objective:'Membangun corroboration antar sumber yang independen.',question:'Bukti mana yang paling relevan untuk menguji otorisasi, occurrence, pola hubungan, dan pemisahan tugas?',source:'Putusan 99 PK/Pid.Sus/2016',sourceUrl:'https://putusan3.mahkamahagung.go.id/direktori/putusan/403cf367970d94f69c977b72679fb80e.html',prov:'primary',reliability:'Tinggi'},
{id:'C-06',releaseStage:3,title:'Formulir transfer yang disita',fact:'Peliputan kontemporer menyebut penyidik menyita 29 formulir transfer dalam proses penyidikan.',objective:'Menghubungkan dokumen instruksi dengan transaksi yang diproses.',question:'Bagaimana Anda akan memastikan populasi 29 formulir tersebut lengkap dan relevan terhadap populasi transaksi yang sedang diuji?',source:'ANTARA, 2011',sourceUrl:'https://www.antaranews.com/berita/252961/penyidik-polri-audit-rekening-milik-malinda-dee',prov:'secondary',reliability:'Sedang-Tinggi'}
],
witnesses:[
{id:'W-01',releaseStage:3,name:'Inong Malinda Dee',role:'Senior Relationship Manager',summary:'Perannya penting untuk memahami hubungan nasabah, asal instruksi transfer, dan bagaimana dokumen transaksi masuk ke proses bank.',source:'Putusan 1607 K/PID.SUS/2012',sourceUrl:'https://putusan3.mahkamahagung.go.id/direktori/putusan/b3eadb9806be6073c8dc468767cf2da5.html',prov:'primary',qa:[
{q:'Apa aspek proses yang perlu diuji dari peran Relationship Manager?',a:'Fokuskan pada bagaimana instruksi nasabah diterima, didokumentasikan, diteruskan, dan dipisahkan dari kewenangan pemrosesan/verifikasi. Catatan perkara menempatkan peran relationship manager sebagai bagian penting dalam rantai transaksi, tetapi aplikasi tidak menambahkan dialog historis yang tidak tersedia.'},
{q:'Apa bukti yang harus dikonfirmasi dari sisi nasabah?',a:'Konfirmasi langsung atas otorisasi, tujuan transaksi, beneficiary yang dikenal, serta pola instruksi sebelumnya. Bukti nasabah harus dibandingkan dengan transfer form dan account activity, bukan berdiri sendiri.'},
{q:'Apa yang belum dapat disimpulkan hanya dari jabatan RM?',a:'Jabatan atau kedekatan dengan nasabah tidak membuktikan sendiri bahwa setiap transaksi tidak sah. Kesimpulan memerlukan bukti otorisasi per transaksi dan corroboration dari sumber lain.'}
]},
{id:'W-02',releaseStage:3,name:'Novianty Iriane',role:'Cash Officer',summary:'Relevan untuk merekonstruksi proses kas dan verifikasi. Putusan PK berikutnya harus diperlakukan terpisah dari analisis kontrol.',source:'Putusan 99 PK/Pid.Sus/2016',sourceUrl:'https://putusan3.mahkamahagung.go.id/direktori/putusan/403cf367970d94f69c977b72679fb80e.html',prov:'primary',qa:[
{q:'Apa yang perlu ditanyakan tentang pemrosesan transfer?',a:'Tanyakan dokumen apa yang diterima, apa yang diperiksa sebelum input/pemrosesan, siapa yang melakukan verifikasi berikutnya, dan bagaimana exception ditangani. Pertanyaan ini menguji desain dan operasi kontrol, bukan menetapkan tanggung jawab pidana.'},
{q:'Bagaimana memisahkan bukti kontrol dari kesimpulan hukum?',a:'Catat apa yang terjadi pada proses dan bukti operasional terlebih dahulu. Secara terpisah, catat bahwa putusan PK berikutnya mengubah disposisi hukum terhadap individu terkait. Keduanya tidak boleh digabungkan menjadi satu kesimpulan.'},
{q:'Bukti tambahan apa yang paling penting?',a:'Log atau catatan pemrosesan, formulir transfer, bukti verifikasi, exception report, dan pola transaksi pembanding pada periode yang sama.'}
]},
{id:'W-03',releaseStage:3,name:'Betharia Panjaitan',role:'Cash Supervisor',summary:'Relevan untuk transaksi bernilai besar, verifikasi, dan konsentrasi fungsi supervisi. Putusan PK berikutnya harus diperlakukan secara akurat.',source:'Putusan 99 PK/Pid.Sus/2016',sourceUrl:'https://putusan3.mahkamahagung.go.id/direktori/putusan/403cf367970d94f69c977b72679fb80e.html',prov:'primary',qa:[
{q:'Apa fakta kontrol yang dapat diuji dari catatan perkara?',a:'Catatan perkara menyebut 18 formulir transfer melewati seorang Cash Supervisor dan delapan transaksi di atas Rp300 juta diverifikasi olehnya. Fakta ini dapat dipakai untuk menguji konsentrasi verifikasi dan efektivitas supervisi.'},
{q:'Apakah delapan verifikasi membuktikan kontrol gagal?',a:'Tidak. Fakta tersebut hanya menunjukkan aktivitas verifikasi. Anda masih perlu menilai kualitas verifikasi, kriteria, bukti yang diperiksa, exception yang muncul, dan pembanding atas transaksi normal.'},
{q:'Apa prosedur lanjutan yang tepat?',a:'Bandingkan seluruh transaksi yang melewati supervisor tersebut dengan populasi transaksi serupa, uji bukti verifikasi, dan telusuri apakah ada pola beneficiary, RM, nilai, atau waktu yang tidak lazim.'}
]},
{id:'W-04',releaseStage:3,name:'Nasabah Citibank',role:'Pemilik rekening',summary:'Keterangan nasabah relevan untuk menguji apakah transaksi benar-benar diotorisasi dan sesuai pola hubungan perbankan.',source:'Putusan dan peliputan persidangan',sourceUrl:'https://www.antaranews.com/berita/285795/sidang-malinda-dee-hadirkan-pihak-citibank',prov:'secondary',qa:[
{q:'Apa pertanyaan konfirmasi paling penting?',a:'Apakah nasabah mengotorisasi transaksi, mengenal penerima, memahami tujuan transaksi, dan pernah memberikan instruksi serupa sebelumnya.'},
{q:'Mengapa konfirmasi nasabah belum cukup?',a:'Karena konfirmasi perlu dicocokkan dengan dokumen instruksi, signature evidence, transaksi aktual, dan jejak proses internal.'},
{q:'Apa risiko hindsight bias?',a:'Setelah kasus diketahui publik, jawaban dan interpretasi dapat dipengaruhi hasil akhir. Karena itu mahasiswa harus selalu kembali ke bukti yang bertanggal dan tersedia pada saat transaksi.'}
]},
{id:'W-05',releaseStage:3,name:'Penyidik',role:'Rekonstruksi dan penyitaan bukti',summary:'Peliputan kontemporer menyebut rekonstruksi proses dan penyitaan 29 formulir transfer.',source:'ANTARA',sourceUrl:'https://www.antaranews.com/berita/253197/malinda-laksanakan-rekonstruksi',prov:'secondary',qa:[
{q:'Apa nilai rekonstruksi proses untuk analisis SIA?',a:'Rekonstruksi membantu menguji siapa melakukan apa, urutan aktivitas, dokumen yang digunakan, serta titik kontrol yang seharusnya mencegah atau mendeteksi transaksi bermasalah.'},
{q:'Apa keterbatasan peliputan media sebagai bukti?',a:'Peliputan adalah sumber sekunder. Gunakan untuk orientasi dan triangulasi, tetapi prioritaskan putusan, dokumen resmi, dan artefak transaksi ketika tersedia.'},
{q:'Bagaimana memperlakukan 29 formulir yang disita?',a:'Sebagai populasi bukti yang perlu diuji kelengkapan, relevansi, dan hubungannya dengan transaksi. Jangan menganggap 29 formulir otomatis mewakili semua transaksi yang dipersoalkan.'}
]}
],
evidence:[
{id:'E-01',releaseStage:1,title:'Putusan MA 1607 K/PID.SUS/2012',desc:'Sumber utama fakta perkara dan rincian transaksi yang dapat ditelusuri.',use:'Fakta perkara, transaksi, aktor, kronologi.',limitation:'Putusan bukan pengganti log sistem bank yang lengkap.',sourceUrl:'https://putusan3.mahkamahagung.go.id/direktori/putusan/b3eadb9806be6073c8dc468767cf2da5.html',prov:'primary',reliability:'Tinggi'},
{id:'E-02',releaseStage:2,title:'Putusan PK 99 PK/Pid.Sus/2016',desc:'Sumber penting untuk SOP, peran Cash Officer/Supervisor, bukti verifikasi, uji tanda tangan, dan disposisi hukum berikutnya.',use:'Analisis kontrol dan nuansa disposisi hukum.',limitation:'Bukti proses tidak boleh dipakai sebagai shortcut untuk menyimpulkan tanggung jawab pidana individu.',sourceUrl:'https://putusan3.mahkamahagung.go.id/direktori/putusan/403cf367970d94f69c977b72679fb80e.html',prov:'primary',reliability:'Tinggi'},
{id:'E-03',releaseStage:3,title:'Peliputan persidangan 117 transfer',desc:'Peliputan ANTARA menyebut sekitar 117 transfer dan kurang lebih 30 nasabah.',use:'Membantu memahami skala dugaan transaksi.',limitation:'Angka agregat sekunder tidak menggantikan daftar transaksi primer.',sourceUrl:'https://www.antaranews.com/berita/285795/sidang-malinda-dee-hadirkan-pihak-citibank',prov:'secondary',reliability:'Sedang-Tinggi'},
{id:'E-04',releaseStage:3,title:'Penyitaan formulir transfer',desc:'Peliputan kontemporer menyebut 29 formulir transfer disita penyidik.',use:'Menghubungkan dokumen instruksi dengan transaksi.',limitation:'Perlu diuji apakah formulir tersebut merupakan populasi lengkap atau hanya bagian barang bukti.',sourceUrl:'https://www.antaranews.com/berita/252961/penyidik-polri-audit-rekening-milik-malinda-dee',prov:'secondary',reliability:'Sedang-Tinggi'},
{id:'E-05',releaseStage:2,title:'Formulir transfer simulasi',desc:'Rekonstruksi visual untuk membantu memahami field dan kontrol; bukan scan formulir Citibank asli.',use:'Memetakan input → verifikasi → otorisasi → posting.',limitation:'Tidak boleh dikutip sebagai bukti historis.',sourceUrl:'',prov:'reconstruction',reliability:'Pembelajaran'},
{id:'E-06',releaseStage:4,title:'Disposisi hukum pasca-PK',desc:'Putusan PK terhadap Novianty Iriane dan Betharia Panjaitan harus dibaca terpisah dari bukti proses/kontrol yang muncul dalam catatan perkara.',use:'Menguji kemampuan membedakan kesimpulan kontrol dan kesimpulan hukum.',limitation:'Tidak menghapus kebutuhan menilai apakah desain/operasi kontrol pada proses transaksi efektif.',sourceUrl:'https://putusan3.mahkamahagung.go.id/direktori/putusan/403cf367970d94f69c977b72679fb80e.html',prov:'primary',reliability:'Tinggi'}
],
procedures:[
{id:'P-01',title:'Konfirmasi otorisasi nasabah',desc:'Cocokkan instruksi transfer dengan konfirmasi nasabah dan dokumentasi pendukung.'},
{id:'P-02',title:'Uji populasi beneficiary berulang',desc:'Identifikasi penerima yang menerima transfer dari lebih dari satu nasabah dan lakukan follow-up berbasis risiko.'},
{id:'P-03',title:'Uji threshold dan verifikasi',desc:'Bandingkan transaksi di sekitar batas verifikasi dengan bukti review dan pola supervisor.'},
{id:'P-04',title:'Reperformance tanda tangan/dokumen',desc:'Perluas pengujian autentisitas secara berbasis risiko; jangan generalisasi dari dua formulir.'},
{id:'P-05',title:'Rekonsiliasi end-to-end',desc:'Telusuri formulir → pemrosesan → posting rekening → beneficiary → account summary.'},
{id:'P-06',title:'Analisis pola pegawai',desc:'Jika data tersedia, uji konsentrasi RM/teller/supervisor dan exception per user.'}
],
decisions:['Kontrol desain memadai tetapi pelaksanaan gagal','Terdapat kelemahan desain dan pelaksanaan kontrol','Bukti belum cukup untuk menyimpulkan','Perlu prosedur investigasi tambahan sebelum kesimpulan']
};